### PR TITLE
Add new pairs (Jan 2022): DOT, SOL, ADA, SHIB, AVAX, FTM, WBTC, LUNA,…

### PR DESCRIPTION
**Pull request by RobMKR**
… ATOM, NEAR

---
This change is [Reviewable](https://reviewable.io/reviews/bit-oasis/coin/22)

### CODE REVIEW

**Review by foowie — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/22)* status: all files reviewed, 14 unresolved discussions (waiting on @RobMKR)

___
*[src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, line 87 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBxV6HDpPJ51yu93IL:-MuBxV6HDpPJ51yu93IM:b-gt659) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/DefaultCryptocurrencyFactory.php#L87)):*
> ```PHP
> 		$this->cryptocurrencies[Cryptocurrency::AVAX] = new Cryptocurrency(Cryptocurrency::AVAX, 18, 'Avalanche');
> 		$this->cryptocurrencies[Cryptocurrency::FTM] = new Cryptocurrency(Cryptocurrency::FTM, 18, 'Fantom');
> 		$this->cryptocurrencies[Cryptocurrency::WBTC] = new Cryptocurrency(Cryptocurrency::WBTC, 18, 'Wrapped Bitcoin');
> ```

Should be 8
___
*[src/BitOasis/Coin/Address/AvalancheAddress.php, line 13 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBxaWY9R3ypjcGk6Cl:-MuBxaWY9R3ypjcGk6Cm:b-uq9xbb) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/AvalancheAddress.php#L13)):*
> ```PHP
>  * For P-Chain and X-Chain needs separate implementation
>  */
> class AvalancheAddress extends EthereumAddress {
> ```

Hmmm I'm thinking if we should call it AvalancheCChainAddress? I'm not sure TBH
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 11 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBy3W3AS1heWgu864v:-MuBy3W3AS1heWgu864w:b-o2cxs8) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L11)):*
> ```PHP
> use BitOasis\Coin\Exception\InvalidAddressException;
> 
> abstract class BaseBech32WithPrefixAddress implements CryptocurrencyAddress {
> ```

BaseBech32WithPrefixAddress

Hmmm ... even though it might be ok, I still don't like that this name does not say that its also implementing tag called "tag" that can be int only.



_Code quote:_
```PHP
BaseBech32WithPrefixAddress
```
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBxiC2ESHaMnOhhfEP:-MuBxiC2ESHaMnOhhfEQ:b-63w6ik) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L12)):*
> ```PHP
> 
> abstract class BaseBech32WithPrefixAddress implements CryptocurrencyAddress {
> 	/** @var string */
> ```

This comment needs some space ... above :D
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 22 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5Ct-8ZJtclZDK8i8:-MuC5Ct-8ZJtclZDK8i9:b35uy1n) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L22)):*
> ```PHP
> 
> 	/**
> 	 * RippleAddress constructor.
> ```

The name :p (just remove that)
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 130 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5O062C47v93dNPku:-MuC5O062C47v93dNPkv:bb6xb9l) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L130)):*
> ```PHP
> 	 */
> 	private function validateAddress($address, $tag = null) {
> 		/** @var CosmosAddressValidator|TerraAddressValidator $validator */
> ```

Huh?
___
*[src/BitOasis/Coin/Address/CosmosAddress.php, line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5ayA5DEoKNosZ8u2:-MuC5ayA5DEoKNosZ8u3:bljb6t3) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/CosmosAddress.php#L12)):*
> ```PHP
>  */
> class CosmosAddress extends BaseBech32WithPrefixAddress implements CryptocurrencyAddress {
> 	/**
> ```

Need some space :P
___
*[src/BitOasis/Coin/Address/FantomAddress.php, line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5jHc5UZUmLq9ivEB:-MuC5jHc5UZUmLq9ivEC:b-sp10gj) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/FantomAddress.php#L12)):*
> ```PHP
>  * For mainnet use another address type
>  */
> class FantomAddress extends EthereumAddress {
> ```

Sooo shall we rename that to FantomERC20Address ?
___
*[src/BitOasis/Coin/Address/Validators/Bech32AddressWithPrefixValidator.php, line 83 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC6Me6ClP_QBVy08z1:-MuC6Me6ClP_QBVy08z2:b588ml9) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/Validators/Bech32AddressWithPrefixValidator.php#L83)):*
> ```PHP
> 	protected function validateTag() {
> 		$tag = $this->tag;
> 		if ($tag !== null && (!is_numeric($tag) || (int)$tag != $tag || (int)$tag <= 0 || (int)$tag > 4294967295)) {
> ```

Can you please confirm that it can be only positive (not zero) number as well as max. tag number?
___
*[src/BitOasis/Coin/Address/Validators/Bech32WithPrefixValidator.php, line 8 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC6_kVAkPBVOGHezzK:-MuC6_kVAkPBVOGHezzL:b-59m9fy) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/Validators/Bech32WithPrefixValidator.php#L8)):*
> ```PHP
>  * @author Robert Mkrtchyan <mkrtchyanrobert@gmail.com>
>  */
> class Bech32WithPrefixValidator {
> ```

Is this used anywhere?



_Code quote:_
```PHP
Bech32WithPrefixValidator
```
___
*[src/BitOasis/Coin/Address/Validators/NearAddressValidator.php, line 22 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC6l6980VIimjm0u8a:-MuC6l6980VIimjm0u8b:b-2xzc13) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/Validators/NearAddressValidator.php#L22)):*
> ```PHP
> 	 */
> 	public function validate() {
> 		if (preg_match('/^[a-f0-9]{64}$/', $this->address) == 0) {
> ```

Only lower case allowed?
___
*[src/BitOasis/Coin/Utils/Bech32/Bech32.php, line 8 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC74Kq04-RhPAt0PaA:-MuC74Kr8c0tvRG1R0Fn:btqoduq) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Utils/Bech32/Bech32.php#L8)):*
> ```PHP
>  * @author Robert Mkrtchyan <mkrtchyanrobert@gmail.com>
>  * @original Bit Wasp
>  * @see https://github.com/Bit-Wasp/bech32
> ```

Is this copy-paste? Any copyright issue/note/mention?
___
*[src/BitOasis/Coin/Utils/Bech32/Bech32.php, line 52 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuFFtTj7IK8DPifNlYj:-MuFFtTj7IK8DPifNlYk:bosg7vc) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Utils/Bech32/Bech32.php#L52)):*
> ```PHP
> 	 */
> 	private function polyMod(array $values, $numValues)
> 	{
> ```

Please reformat code { and newline
___
*[tests/unit/BitOasis/Coin/Address/NearAddressTest.php, line 31 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuFICQQDhe6pcQ_cZyW:-MuFICQQDhe6pcQ_cZyX:b-r6f6t1) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/tests/unit/BitOasis/Coin/Address/NearAddressTest.php#L31)):*
> ```PHP
> 		return [
> 			// Any hex string with 64 length
> 			['efbad19288fe961664f70b03b122541b46244cb287557e26b17c2b0926c6c61b'],
> ```

How about https://explorer.near.org/accounts/pixeltoken.near ? Is this valid address/account?

**Review by RobMKR — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/22)* status: all files reviewed, 14 unresolved discussions (waiting on @foowie)

___
*[src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, line 87 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBxV6HDpPJ51yu93IL:-MuFTb3LEF3xkaA25peX:b-896fix) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/DefaultCryptocurrencyFactory.php#L87)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Should be 8
</blockquote></details>

Done.
___
*[src/BitOasis/Coin/Address/AvalancheAddress.php, line 13 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBxaWY9R3ypjcGk6Cl:-MuFTdGJC4ndbwlEL2Ld:b-lleoq8) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/AvalancheAddress.php#L13)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Hmmm I'm thinking if we should call it AvalancheCChainAddress? I'm not sure TBH
</blockquote></details>

I was thinking the same to be honest, then just remember, that we are supporting only one network, and whenever we will start to support multiple networks, we will have to rewrite a few things here. But we can rename it now.
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 11 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBy3W3AS1heWgu864v:-MuFUgnD5xlRRrI38xPS:balngc9) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L11)):*
> BaseBech32WithPrefixAddress
Agree, need to rename. BaseBech32AddressWithPrefixAndTag
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuBxiC2ESHaMnOhhfEP:-MuFVRPmB2HDmf5_pZTQ:bb6un1j) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L12)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

This comment needs some space ... above :D
</blockquote></details>

Done
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 22 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5Ct-8ZJtclZDK8i8:-MuFVOr1Ct2SYOqcR6UT:b32v39) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L22)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

The name :p (just remove that)
</blockquote></details>

))
___
*[src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php, line 130 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5O062C47v93dNPku:-MuFW5_j4_N9dJyjL77t:b-rsdvk9) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/BaseBech32WithPrefixAddress.php#L130)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Huh?
</blockquote></details>

:facepalm: I knew I'm tired :D 
___
*[src/BitOasis/Coin/Address/CosmosAddress.php, line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5ayA5DEoKNosZ8u2:-MuFWZla1CHU2odOBtux:b-896fix) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/CosmosAddress.php#L12)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Need some space :P
</blockquote></details>

Done.
___
*[src/BitOasis/Coin/Address/FantomAddress.php, line 12 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC5jHc5UZUmLq9ivEB:-MuFXgjy-QOaa4_shwvR:b-80tlqk) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/FantomAddress.php#L12)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Sooo shall we rename that to FantomERC20Address ?
</blockquote></details>

Sure.
___
*[src/BitOasis/Coin/Address/Validators/Bech32AddressWithPrefixValidator.php, line 83 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC6Me6ClP_QBVy08z1:-MuF_y2v9oxNJ2ox9tKq:blyk9ub) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/Validators/Bech32AddressWithPrefixValidator.php#L83)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Can you please confirm that it can be only positive (not zero) number as well as max. tag number?
</blockquote></details>

String and/or numbers

So replaced with just not empty string validation
___
*[src/BitOasis/Coin/Address/Validators/Bech32WithPrefixValidator.php, line 8 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC6_kVAkPBVOGHezzK:-MuFYrf3772jQi84fqB9:b-ab7knj) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/Validators/Bech32WithPrefixValidator.php#L8)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Is this used anywhere?
</blockquote></details>

Nope, removed
___
*[src/BitOasis/Coin/Address/Validators/NearAddressValidator.php, line 22 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC6l6980VIimjm0u8a:-MuFZhz5514_S8cZSrhb:bkuzfsl) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Address/Validators/NearAddressValidator.php#L22)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Only lower case allowed?
</blockquote></details>

Fully replaced with new logic.
___
*[src/BitOasis/Coin/Utils/Bech32/Bech32.php, line 8 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuC74Kq04-RhPAt0PaA:-MuF_Sh2-xYyOQK8jtDt:brg73ow) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Utils/Bech32/Bech32.php#L8)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Is this copy-paste? Any copyright issue/note/mention?
</blockquote></details>

https://github.com/Bit-Wasp/bech32/blob/master/LICENCE

Not sure what I need to add for copyright



_Code quote:_
```PHP
https://github.com/Bit-Wasp/bech32
```
___
*[src/BitOasis/Coin/Utils/Bech32/Bech32.php, line 52 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuFFtTj7IK8DPifNlYj:-MuF_kX2BkiQO3rIcE1D:b-896fix) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/src/BitOasis/Coin/Utils/Bech32/Bech32.php#L52)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

Please reformat code { and newline
</blockquote></details>

Done.
___
*[tests/unit/BitOasis/Coin/Address/NearAddressTest.php, line 31 at r1](https://reviewable.io/reviews/bit-oasis/coin/22#-MuFICQQDhe6pcQ_cZyW:-MuF_mi9CsjWZIx-FM3J:b-6cy0h7) ([raw file](https://github.com/bit-oasis/coin/blob/61b5f6177702e05c7e4ff690d6798a576996c709/tests/unit/BitOasis/Coin/Address/NearAddressTest.php#L31)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

How about https://explorer.near.org/accounts/pixeltoken.near ? Is this valid address/account?
</blockquote></details>

Added new validation rules

**Review by foowie — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/22)* status: all files reviewed, 3 unresolved discussions (waiting on @RobMKR)

___
*[src/BitOasis/Coin/Address/Validators/NearAddressValidator.php, line 46 at r4](https://reviewable.io/reviews/bit-oasis/coin/22#-MuVZimc1tXhOZKfIOVU:-MuVZimc1tXhOZKfIOVV:b82ttbd) ([raw file](https://github.com/bit-oasis/coin/blob/8f1ab2286db926d3e38ae75a603ed0e56bf1a3b0/src/BitOasis/Coin/Address/Validators/NearAddressValidator.php#L46)):*
> ```PHP
> 		}
> 
> 		list($addressName, $addressDomain) = explode('.', $this->address);
> ```

test.near.xxx
___
*[src/BitOasis/Coin/Address/Validators/NearAddressValidator.php, line 52 at r4](https://reviewable.io/reviews/bit-oasis/coin/22#-MuV_87y834Buk33MUYY:-MuV_87y834Buk33MUYZ:b-2chhyz) ([raw file](https://github.com/bit-oasis/coin/blob/8f1ab2286db926d3e38ae75a603ed0e56bf1a3b0/src/BitOasis/Coin/Address/Validators/NearAddressValidator.php#L52)):*
> ```PHP
> 		}
> 
> 		if (preg_match('/^[a-zA-Z0-9][a-zA-Z0-9_-]*(?<!_|-)$/', $addressName) == 0) {
> ```

'/^[a-zA-Z0-9]([a-zA-Z0-9_-]{0,1}[a-zA-Z0-9]+)*(?<!_|-)$/'



_Code quote:_
```PHP
'/^[a-zA-Z0-9][a-zA-Z0-9_-]*(?<!_|-)$/'
```
___
*[tests/unit/BitOasis/Coin/Address/NearAddressTest.php, line 31 at r3](https://reviewable.io/reviews/bit-oasis/coin/22#-MuKTndO1lEmyuKx0dDd:-MuKTndO1lEmyuKx0dDe:b-2xkm9l) ([raw file](https://github.com/bit-oasis/coin/blob/7130495e9e8cd0a67276c86f514f8ae3ce053a94/tests/unit/BitOasis/Coin/Address/NearAddressTest.php#L31)):*
> ```PHP
> 			['-invalid.near'],
> 			['invalid-_near'],
> 			['invalid.test'],
> ```

It will be good to check all cases including too long address (too short not possible)

**Review by RobMKR — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/22)* status: all files reviewed, 3 unresolved discussions (waiting on @foowie)

___
*[src/BitOasis/Coin/Address/Validators/NearAddressValidator.php, line 46 at r4](https://reviewable.io/reviews/bit-oasis/coin/22#-MuVZimc1tXhOZKfIOVU:-MuVcMZs-hoy6Kln5mXO:bb6un1j) ([raw file](https://github.com/bit-oasis/coin/blob/8f1ab2286db926d3e38ae75a603ed0e56bf1a3b0/src/BitOasis/Coin/Address/Validators/NearAddressValidator.php#L46)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

test.near.xxx
</blockquote></details>

Done
___
*[src/BitOasis/Coin/Address/Validators/NearAddressValidator.php, line 52 at r4](https://reviewable.io/reviews/bit-oasis/coin/22#-MuV_87y834Buk33MUYY:-MuVcIsP3cS7NnlyvHHy:bb6un1j) ([raw file](https://github.com/bit-oasis/coin/blob/8f1ab2286db926d3e38ae75a603ed0e56bf1a3b0/src/BitOasis/Coin/Address/Validators/NearAddressValidator.php#L52)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

'/^[a-zA-Z0-9]([a-zA-Z0-9_-]{0,1}[a-zA-Z0-9]+)*(?<!_|-)$/'
</blockquote></details>

Done
___
*[tests/unit/BitOasis/Coin/Address/NearAddressTest.php, line 31 at r3](https://reviewable.io/reviews/bit-oasis/coin/22#-MuKTndO1lEmyuKx0dDd:-MuVcKNo-Cg2BOur-8o6:bb6un1j) ([raw file](https://github.com/bit-oasis/coin/blob/7130495e9e8cd0a67276c86f514f8ae3ce053a94/tests/unit/BitOasis/Coin/Address/NearAddressTest.php#L31)):*
<details><summary><i>Previously, foowie (Daniel Robenek) wrote…</i></summary><blockquote>

It will be good to check all cases including too long address (too short not possible)
</blockquote></details>

Done

**Review by foowie — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bit-oasis/coin/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RobMKR)

**Pull request merged**
